### ISSUE TITLE
WS-clean up tool- Question about config file

### ISSUE THREAD

**Issue by monika1311-me** [whitesource-ps/ws-cleanup-tool#22]
I have few concerns regarding the implementation of WS-Clean up tool:
In order to run this utility, we have to set the parameters in params.config file and below are the parameters which are not clear to me:
• IncludedProductTokens- Will this include and work on only the products for which I provide the token here.
• ExcludedProductTokens- Is it mandatory to add tokens here. Doesn't it consider rest of the projects as excluded if I add some tokens to IncludedProductTokens parameter.
• *DryRun- The statement is confusing. Like If I set it to True then what will it do?
• ReportsDir- Will this be the location on my machine.

**Comment by tamari-oz** [comment]
**IncludedProductTokens** - If this is empty it will work on all the products. If you want that it will only work on specific products, you can state the product tokens comma separated.
**ExcludedProductTokens** - Optional parameter, if you want to exclude a product from the scope (mostly for scenarios when you work on all the products within the org.
**DryRun** - This is for testing purposes, when you don't want to actually delete yet, just to review what will the tool do.
**ReportsDir** - where you want the archiving will happen in on the machine running your tool.

I hope this clarify it.
