### ISSUE TITLE
[BUG] [ws-tool-name] Variables IncludedProductTokens and ExcludedProductTokens are reversed in the params.config file

### ISSUE THREAD

**Issue by radiyman** [whitesource-ps/ws-cleanup-tool#34]
**Bug Description**  
Variables IncludedProductTokens and
ExcludedProductTokens are reversed in the params.config file.

Function call 
`conf = ws_cleanup_tool.cleanup_tool.parse_config()`
Writes the values from the IncludedProductTokens params.config file to the conf.excluded_product_tokens variable and vice versa.
Accordingly, ws_cleanup_tool incorrectly uses wrong data from the IncludedProductTokens variables and
ExcludedProductTokens .

**Steps to Reproduce**  
1. Add ExcludedProductTokens and  IncludedProductTokens nj params.config file
2. run ws_cleanup_tool  params.config
3. See that products added to ExcludedProductTokens are marked for deletion.
when debugging, you can see that these values got into the IncludedProductTokens variable.

**Environment Details**  
 - OS: [e.g. Ubuntu 20.04]
 - Version [ws-sdk~=0.8.0.1
ws-cleanup-tool~=0.2.1]

**Comment by radiyman** [comment]
My apologies.
Yesterday, when I was checking everything, I mixed up these variables in places when outputting them.
The description of variables is very confusing.
I read it like this:
IncludedProductTokens - list of included products (products included to cleaning list - we need to clean them)
ExcludedProductTokens - list of excluded products (products excluded from cleaning list - we do not need to clean them)
it would be nice if you clarified included or excluded from which list.

**Comment by tamari-oz** [comment]
I changed the documentation a bit hope it is clearer now,
