### ISSUE TITLE
[BUG] [ws-tool-name] Issue ws_cleanup_tool does not read the SkipProjectDeletion and SkipReportGeneration variables from the params.config file.

### ISSUE THREAD

**Issue by radiyman** [whitesource-ps/ws-cleanup-tool#36]
ws_cleanup_tool does not read the SkipProjectDeletion and SkipReportGeneration variables from the params.config file.
The README.md file contains the description of the variables for the Params.config file:
```
SkipReportGeneration - Whether to skip report generation
SkipProjectDeletion - whether to skip project deletion
```
At the moment, the cleanup_tool.py code only implements reading these variables from the environment variables SKIP_REPORT_GENERATION, SKIP_PROJECT_DELETION.
https://github.com/whitesource-ps/ws-cleanup-tool/blob/master/ws_cleanup_tool/cleanup_tool.py#L16

**Environment Details**  
 - OS: [e.g. Ubuntu 20.04]
 - Version [ws-sdk~=0.8.0.1
ws-cleanup-tool~=0.2.1]

**Comment by NatalyaDalid** [comment]
Hello @radiyman ,
Thank you for this finding.
Please use the latest version, v0.2.5, of the cleanup tool containing the fix.

Thanks,
WhiteSource PS Team

**Comment by rammatzkvosky** [comment]
Hello @radiyman ,

Did the fixed version work for you?

You can also check it with our [latest one](https://pypi.org/project/ws-sbom-generator/22.9.1/#history) .
