### ISSUE TITLE
[BUG] [ws-cleanup-tool] Cannot connect

### ISSUE THREAD

**Issue by yoannAtB** [whitesource-ps/ws-cleanup-tool#47]
**Bug Description**  
I download version 0.32 of the ws-cleanup-tool and executed the ws_cleanup_tool command and I got error "Invalid organization token".

**Steps to Reproduce**  
1. Run the following command:
ws_cleanup_tool -a https://saas-eu.whitesourcesoftware.com-r 2 -m FilterProjectsByLastCreatedCopies -u <USER_KEY>  -t <ORG_TOKEN> -y true
where  parameter are taken from:
<USER_KEY> : Active (Service User) under Admin -> Users and use the copy token 
<ORG_TOKEN> : Api Key is taken from Integrate API key

2. See error:
DEBUG 22-06-01 10:55:42 19752 ws_sdk.ws_utilities: Executing command: ['java', '-version']
DEBUG 22-06-01 10:55:42 19752 ws_sdk.ws_utilities: Java version: '1.8.0_321'
DEBUG 22-06-01 10:55:42 19752 ws_sdk.ws_utilities: Executing command: ['java', '-Djava.io.tmpdir=c:/tmp/ws-sdk', '-jar', 'c:/tmp/ws-sdk\\wss-unified-agent.jar', '-v', '-noConfig', 'True ']
DEBUG 22-06-01 10:55:44 19752 ws_sdk.client: UA executed successfully. Return Code 0. Message: 22.5.1

DEBUG 22-06-01 10:55:44 19752 ws_sdk.client: Local WhiteSource Unified Agent version 22.5.1
DEBUG 22-06-01 10:55:44 19752 ws_sdk.ws_utilities: Calling url: https://api.github.com/repos/whitesource/unified-agent-distribution/releases/latest
DEBUG 22-06-01 10:55:45 19752 ws_sdk.ws_utilities: Latest Unified Agent version: v22.5.1
DEBUG 22-06-01 10:55:45 19752 ws_sdk.client: Skipping WhiteSource Unified Agent update
INFO 22-06-01 10:55:45 19752 cleanup_tool: Starting project cleanup in 'FilterProjectsByUpdateTime' mode. Generating 0 report types with 5 threads
DEBUG 22-06-01 10:55:45 19752 cleanup_tool: Getting all products
DEBUG 22-06-01 10:55:45 19752 ws_sdk.app: Calling: https://saas-eu.whitesourcesoftware.com/api/v1.3 with requestType: getOrganizationProductVitals
DEBUG 22-06-01 10:55:45 19752 ws_sdk.app: API returned errorCode getOrganizationProductVitals call on None message: {"errorCode":1002,"errorMessage":"Invalid organization token"}
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\users1\AppData\Roaming\Python\Python39\Scripts\ws_cleanup_tool.exe\__main__.py", line 7, in <module>
  File "C:\Users\users1\AppData\Roaming\Python\Python39\site-packages\ws_cleanup_tool\cleanup_tool.py", line 410, in main
    products_to_clean = get_products_to_archive(conf.included_product_tokens, conf.excluded_product_tokens)
  File "C:\Users\users1\AppData\Roaming\Python\Python39\site-packages\ws_cleanup_tool\cleanup_tool.py", line 165, in get_products_to_archive
    prods = conf.ws_conn.get_products()
  File "C:\Users\users1\AppData\Roaming\Python\Python39\site-packages\ws_sdk\app.py", line 51, in wrapper
    return function.__call__(*args, **kwargs)
  File "C:\Users\users1\AppData\Roaming\Python\Python39\site-packages\ws_sdk\app.py", line 726, in get_products
    products = self._generic_get(get_type="ProductVitals")['productVitals']
  File "C:\Users\users1\AppData\Roaming\Python\Python39\site-packages\ws_sdk\app.py", line 264, in _generic_get
    return self.call_ws_api(request_type=f"get{token_type.capitalize()}{get_type}", kv_dict=kv_dict)
  File "C:\Users\users1\AppData\Roaming\Python\Python39\site-packages\ws_sdk\app.py", line 232, in call_ws_api
    __handle_ws_server_errors(resp.text)
  File "C:\Users\users1\AppData\Roaming\Python\Python39\site-packages\ws_sdk\app.py", line 206, in __handle_ws_server_errors
    raise WsSdkServerGenericError(body[token], error)
ws_sdk.ws_errors.WsSdkServerGenericError: Generic error on token: 'None'. Error: {"errorCode":1002,"errorMessage":"Invalid organization token"}

**Environment Details**  
 - OS: Windows
 - Python 3.9

**Comment by NatalyaDalid** [comment]
Hi @yoannAtB,

I have noticed that there is no space between the URL and the -r : `-a https://saas-eu.whitesourcesoftware.com-r/ 2`
If this is not the case, please share the name of your Organization for a more detailed investigation.

Thanks,
Mend PS Team

**Comment by yoannAtB** [comment]
Hi @NatalyaDalid,
It is a typo when I copy the script in the GitHub description but when the script is executed there is a space.
here is the following script
ws_cleanup_tool -a https://saas-eu.whitesourcesoftware.com -r 2 -m FilterProjectsByUpdateTime -u xxx -t xxx -i "" -y true
I opened a ticket in mend support the details are visible in case: 00093538

**Comment by NatalyaDalid** [comment]
Hi @yoannAtB ,

Please change the parameter of the orgToken to be -k (instead of -t).
There was a typo in the examples section and it has been fixed.

Please let us know if there are any other issues.

Thanks,
Mend PS Team

**Comment by yoannAtB** [comment]
Hi Nathalya, 

Indeed with the -k option, it is working now.

Now when i run the following command:
ws_cleanup_tool -a https://saas-eu.whitesourcesoftware.com/  -m FilterProjectsByUpdateTime -u xxx -k xxx -i "" 

DEBUG 22-06-16 08:47:43 42568 ws_sdk.app: API getProductProjectVitals call on productToken f020cc2c18b04f2a8498efd72761a88527349353afb24aa193bb5d51e5c6d0aa succeeded
INFO 22-06-16 08:47:43 42568 cleanup_tool: Handling product: xxx number of projects: 10
INFO 22-06-16 08:47:43 42084 cleanup_tool: Project names for cleanup check: []
INFO 22-06-16 08:47:43 42084 cleanup_tool: Found total 0 projects to clean up (0 reports will be produced)
INFO 22-06-16 08:47:43 42084 cleanup_tool: Skipping Report Generation
INFO 22-06-16 08:47:43 42084 cleanup_tool: Skipping Project Deletion
INFO 22-06-16 08:47:43 42084 cleanup_tool: Project Cleanup has been finished. Run time: 0:00:04.897084

the output shows 10 projects listed and nothing to clean up.
The "Skipping Project Deletion" is skipped.
How can we delete these 10 projects?

**Comment by NatalyaDalid** [comment]
Hu @yoannAtB ,
Please set Skipping Project Deletion" to False by -j False. I will also change the default to False.

**Comment by yoannAtB** [comment]
Hi Natalya,
I also tried this command: ws_cleanup_tool -a https://saas-eu.whitesourcesoftware.com  -u xxx -k xxx -i xxx -j False
But the result is the same:
INFO 22-06-17 14:41:39 38184 cleanup_tool: Handling product: xxx number of projects: 10
INFO 22-06-17 14:41:39 7696 cleanup_tool: Project names for cleanup check: []
INFO 22-06-17 14:41:39 7696 cleanup_tool: Found total 0 projects to clean up (0 reports will be produced)
INFO 22-06-17 14:41:39 7696 cleanup_tool: Skipping Report Generation
INFO 22-06-17 14:41:39 7696 cleanup_tool: Skipping Project Deletion
INFO 22-06-17 14:41:39 7696 cleanup_tool: Project Cleanup has been finished. Run time: 0:00:06.735035

**Comment by NatalyaDalid** [comment]
Hi @yoannAtB ,
Have you downloaded a new version (v0.3.3) when you were testing? if not please pull the newest one = 0.3.4.

Please let us know if there is any issue.
Thanks
Natalya

**Comment by yoannAtB** [comment]
Hi @NatalyaDalid 

I download and test with the version 0.3.4 and the result is the same.

INFO 22-06-20 08:14:22 20024 cleanup_tool: Handling product: xxx of projects: 10
INFO 22-06-20 08:14:22 21668 cleanup_tool: Project names for cleanup check: []
INFO 22-06-20 08:14:22 21668 cleanup_tool: Found total 0 projects to clean up (0 reports will be produced)
INFO 22-06-20 08:14:22 21668 cleanup_tool: Skipping Report Generation
INFO 22-06-20 08:14:22 21668 cleanup_tool: Skipping Project Deletion
INFO 22-06-20 08:14:22 21668 cleanup_tool: Project Cleanup has been finished. Run time: 0:00:05.758344

**Comment by NatalyaDalid** [comment]
Hey @yoannAtB ,

It sounds a bit strange. Could you please double-check by `pip list` command that the version is 0.3.4? 

Thanks,
Natalya

**Comment by yoannAtB** [comment]
Hey @NatalyaDalid 

the result of pip list is :
pip list
Package             Version
------------------- ---------
applicationinsights 0.11.10
azure-core          1.21.1
azure-cosmos        4.3.0b1
bcrypt              3.2.0
cached-property     1.5.2
certifi             2021.10.8
cffi                1.15.0
chardet             3.0.4
charset-normalizer  2.0.9
click               8.0.3
colorama            0.4.4
configparser        5.2.0
cryptography        36.0.1
DateTime            4.4
decorator           5.1.1
docker              3.7.3
docker-compose      1.24.0
docker-pycreds      0.4.0
dockerpty           0.4.1
docopt              0.6.2
idna                2.7
iotedgehubdev       0.11.1
jsonpath-rw         1.4.0
jsonschema          2.6.0
paramiko            2.9.2
pip                 22.1.1
ply                 3.11
pycparser           2.21
PyNaCl              1.5.0
pyOpenSSL           21.0.0
pypiwin32           223
pytz                2022.1
pywin32             303
PyYAML              4.2b4
requests            2.27.1
setuptools          56.0.0
six                 1.16.0
texttable           0.9.1
urllib3             1.24.3
websocket-client    0.59.0
ws-cleanup-tool     0.3.2
ws-sdk              0.9.0.8
zope.interface      5.4.0

**Comment by yoannAtB** [comment]
Hi @NatalyaDalid ,

Indeed now it is all good :)

Thank you.
