### ISSUE TITLE
[BUG] [ws-cleanup-tool] Filtering for project tags does not work

### ISSUE THREAD

**Issue by RalfVidispine** [whitesource-ps/ws-cleanup-tool#62]
**Bug Description**  
Filtering for project tags does not work. The command line option `-g productive:true` results in no projects - even thought one project has the tag `productive` set to `true`.

**Steps to Reproduce**  
1. Scan a project 
2. Add the tag `productive` to the project via Mend's UI and set it to `true`
3. Run the `ws-cleanup-tool` w/o the `-p` option and with `-r 1 -y true`: it will list all projects in the organisation (to be expected)
4. Run the `ws-cleanup-tool` with the same options as before but add `-g productive:true` : it will list no projects at all

**Expected Behavior**  
`ws-cleanup-tool` should find all projects with tag `productive=true` when specifying the option `-g productive:true`

**Comment by RalfEckstein** [comment]
When debugging the tool I can see that the `project_metadata_d` property of the project is not filled by `ws_sdk`. Within `ws_sdk` I can see that the `project_metadata_d` property is filled by parsing the `lastScanComment` property. Shouldn't it use the `getProjectTags` API call for this?

**Comment by RalfEckstein** [comment]
Hi @rammatzkvosky,

are there any news on this item? 

We'd like to build our housekeeping process for cleaning up old projects based on tags. So working tag filtering support would be essential for this.

Thanks, Ralf

**Comment by rammatzkvosky** [comment]
Hi @RalfEckstein ,

We are examining it.
I will update you in advance with our findings.

**Comment by RalfEckstein** [comment]
Hi @rammatzkvosky,
could you please give me an update on the current status?
Thx!

**Comment by rammatzkvosky** [comment]
Hi @RalfEckstein ,

Apologize for the delay.
I found the root cause for this issue and will share with you a pre-release version ( at test.pypi )  by the beginning of next week.

**Comment by ramibo** [comment]
Hi @RalfEckstein ,

We are in a testing phase and have the following pre-release test version if you want to try ( make sure to use the `--DryRun` option set to `true` as this is not a final version) : 
```console
pip3 install -i https://test.pypi.org/pypi/ --extra-index-url https://pypi.org/simple ws-cleanup-tool==22.12.4.1a1 
```

I will keep you updated once we will have a final release.
