### ISSUE TITLE
[Question] [ws-cleanup-tool] What are the possible values for -t report types?

### ISSUE THREAD

**Issue by jesse-mend** [whitesource-ps/ws-cleanup-tool#64]
**Question**  
The readme lists `-t REPORT_TYPES, --reportTypes : Report Types to generate (comma seperated list)` but there is no further information about what types are supported. PDF? HTML? JSON? 

No matter what I put after `-t` I get "Generating 0 report types". Please help me understand the options available. Thank you!

**Comment by clindseyws** [comment]
Jesse, the available reports are listed at the bottom of the readme documentation.  

Please let me know if you have any more questions.

**Comment by jesse-mend** [comment]
Thanks Chris!
