### ISSUE TITLE
[BUG] [ws-cleanup-tool] The tool scans every product / project regardless of configured scope

### ISSUE THREAD

**Issue by jesse-mend** [whitesource-ps/ws-cleanup-tool#67]
**Bug Description**  
Even when I specify the scope, for example included products with `-i productToken` or tags using `-g key:value`, the tool still attempts to get information about every product / project in my organization. This takes a very long time, especially for clients with very large organizations (who are the ones most likely to use the cleanup tool).

**Steps to Reproduce**  
1. Run the tool using `-i` or `-g` flag
2. Observe the tool querying `getProductProjectVitals` on all products in the org.

**Expected Behavior**  
Only the specified products / tags are scanned.

**Comment by rammatzkvosky** [comment]
Hi @jesse-mend ,

The same was reported [here](https://github.com/whitesource-ps/ws-cleanup-tool/issues/62) .

**Comment by jesse-mend** [comment]
Hi @rammatzkvosky I think the issue here is distinct: the tool ignores the specified scope when evaluating products / projects. Every single product / project is iterated through, and for large organizations this takes a very long time.

My expectation would be that specifying a product with `-i productToken` would only run the tool on that product.
