### ISSUE TITLE
[BUG] [ws-cleanup-tool]- One of the project tokens hasn't been found in the provided products

### ISSUE THREAD

**Issue by tolmaidis** [whitesource-ps/ws-cleanup-tool#75]
**Bug Description**  
When I use the following commands, I get back an error that the project or the pattern is not found in the product, but this is wrong because I manually verified that it exists in both cases:

Commands:
- ws_cleanup_tool -r 10 -m FilterProjectsByUpdateTime -u **** -k **** -i **** -n my-test.jar -y true
---> ERROR:
cleanup_tool: pattern my-test.jar hasn't been found for any project in the provided products

or

- ws_cleanup_tool -r 10 -m FilterProjectsByUpdateTime -u **** -k **** -i **** -x **** -y true
---> ERROR:
One of the project tokens hasn't been found in the provided products

**Environment Details**  
 - Version: 22.8.5

**Comment by rammatzkvosky** [comment]
Dear @tolmaidis .

I tried reproducing your reported scenario but did not face it on my test.

![image](https://user-images.githubusercontent.com/41573396/217237526-06fd0a75-efe5-4ca5-901a-2ff39e21e96e.png)

Kindly send your Mend organization details (Server URL and org name / API key ) to ps@whitesourcesoftware.com so we can check on our side.

**Comment by tolmaidis** [comment]
I have provided the information requested.

**Comment by tidharm** [comment]
@tolmaidis we've just released [v23.2.1](https://pypi.org/project/ws-cleanup-tool/), kindly verify if it addresses this issue and let us know.

**Comment by tolmaidis** [comment]
@tidharm 
Thank you for addressing this issue in the new release (v23.2.1). I have verified that the issue has been resolved and everything is working as expected now.
